# Generated by Django 6.0.3 on 2026-05-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifier',
            name='message_template',
            field=models.TextField(blank=True, default='', help_text='Custom message body. Available variables: {status}, {status_emoji}, {imports}, {failures}, {downloads}, {duration}, {share_url}, {run_id}, {triggered_by}, {date}, {time}. Leave blank to use the auto-generated message.'),
        ),
        migrations.AddField(
            model_name='notifier',
            name='title_template',
            field=models.TextField(blank=True, default='', help_text='Custom notification title. Leave blank for default.'),
        ),
        migrations.CreateModel(
            name='RunShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=86, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_token', to='webapp.run')),
            ],
            options={
                'verbose_name': 'Run Share Token',
            },
        ),
    ]
