# Generated by Django 6.0.3 on 2026-05-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_share_token_and_notifier_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=300)),
                ('auth', models.CharField(max_length=100)),
                ('device_label', models.CharField(blank=True, help_text='Human-readable label, e.g. "iPhone 15 Pro - Safari"', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to='webapp.notifier')),
            ],
            options={
                'verbose_name': 'WebPush Subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
