# Generated by Django 4.2.30 on 2026-06-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_type',
            field=models.CharField(choices=[('full', 'Full'), ('targeted', 'Targeted')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='targeted_recipes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
